/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MentorshipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accepted"
      | "addMentorship"
      | "balances"
      | "confidentialProtocolId"
      | "getMeetLink"
      | "getMentor"
      | "isAccepted"
      | "joinMentorship"
      | "mentors"
      | "nonces"
      | "owner"
      | "refund"
      | "requests"
      | "setUSDC"
      | "submitDecryptedLink"
      | "usdc"
      | "withdrawForMentor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LinkDecryptedOnChain"
      | "LinkSubmitted"
      | "MentorWithdraw"
      | "MentorshipAdded"
      | "PublicDecryptionVerified"
      | "RefundProcessed"
      | "UserAccepted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accepted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addMentorship",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMeetLink",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMentor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAccepted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinMentorship",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mentors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUSDC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDecryptedLink",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawForMentor",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "accepted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addMentorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMeetLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMentor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAccepted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinMentorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mentors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUSDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitDecryptedLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawForMentor",
    data: BytesLike
  ): Result;
}

export namespace LinkDecryptedOnChainEvent {
  export type InputTuple = [mentor: AddressLike, user: AddressLike];
  export type OutputTuple = [mentor: string, user: string];
  export interface OutputObject {
    mentor: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LinkSubmittedEvent {
  export type InputTuple = [requestId: BigNumberish, submitter: AddressLike];
  export type OutputTuple = [requestId: bigint, submitter: string];
  export interface OutputObject {
    requestId: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MentorWithdrawEvent {
  export type InputTuple = [mentor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [mentor: string, amount: bigint];
  export interface OutputObject {
    mentor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MentorshipAddedEvent {
  export type InputTuple = [
    mentor: AddressLike,
    price: BigNumberish,
    version: BigNumberish
  ];
  export type OutputTuple = [mentor: string, price: bigint, version: bigint];
  export interface OutputObject {
    mentor: string;
    price: bigint;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundProcessedEvent {
  export type InputTuple = [
    mentor: AddressLike,
    user: AddressLike,
    requestId: BigNumberish
  ];
  export type OutputTuple = [mentor: string, user: string, requestId: bigint];
  export interface OutputObject {
    mentor: string;
    user: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAcceptedEvent {
  export type InputTuple = [
    mentor: AddressLike,
    user: AddressLike,
    requestId: BigNumberish
  ];
  export type OutputTuple = [mentor: string, user: string, requestId: bigint];
  export interface OutputObject {
    mentor: string;
    user: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Mentorship extends BaseContract {
  connect(runner?: ContractRunner | null): Mentorship;
  waitForDeployment(): Promise<this>;

  interface: MentorshipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accepted: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  addMentorship: TypedContractMethod<
    [meetLinkCipher: BytesLike, proof: BytesLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMeetLink: TypedContractMethod<[mentor: AddressLike], [bigint], "view">;

  getMentor: TypedContractMethod<
    [mentor: AddressLike],
    [[string, bigint, bigint]],
    "view"
  >;

  isAccepted: TypedContractMethod<
    [mentor: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  joinMentorship: TypedContractMethod<
    [mentor: AddressLike],
    [void],
    "nonpayable"
  >;

  mentors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint] & {
        mentor: string;
        meetLink: string;
        price: bigint;
        version: bigint;
      }
    ],
    "view"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, string] & {
        mentor: string;
        user: string;
        price: bigint;
        expiry: bigint;
        fulfilled: boolean;
        cipherHandle: string;
      }
    ],
    "view"
  >;

  setUSDC: TypedContractMethod<[_usdc: AddressLike], [void], "nonpayable">;

  submitDecryptedLink: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  withdrawForMentor: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accepted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "addMentorship"
  ): TypedContractMethod<
    [meetLinkCipher: BytesLike, proof: BytesLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMeetLink"
  ): TypedContractMethod<[mentor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMentor"
  ): TypedContractMethod<
    [mentor: AddressLike],
    [[string, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAccepted"
  ): TypedContractMethod<
    [mentor: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinMentorship"
  ): TypedContractMethod<[mentor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mentors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint] & {
        mentor: string;
        meetLink: string;
        price: bigint;
        version: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, string] & {
        mentor: string;
        user: string;
        price: bigint;
        expiry: bigint;
        fulfilled: boolean;
        cipherHandle: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setUSDC"
  ): TypedContractMethod<[_usdc: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitDecryptedLink"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawForMentor"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "LinkDecryptedOnChain"
  ): TypedContractEvent<
    LinkDecryptedOnChainEvent.InputTuple,
    LinkDecryptedOnChainEvent.OutputTuple,
    LinkDecryptedOnChainEvent.OutputObject
  >;
  getEvent(
    key: "LinkSubmitted"
  ): TypedContractEvent<
    LinkSubmittedEvent.InputTuple,
    LinkSubmittedEvent.OutputTuple,
    LinkSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "MentorWithdraw"
  ): TypedContractEvent<
    MentorWithdrawEvent.InputTuple,
    MentorWithdrawEvent.OutputTuple,
    MentorWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "MentorshipAdded"
  ): TypedContractEvent<
    MentorshipAddedEvent.InputTuple,
    MentorshipAddedEvent.OutputTuple,
    MentorshipAddedEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RefundProcessed"
  ): TypedContractEvent<
    RefundProcessedEvent.InputTuple,
    RefundProcessedEvent.OutputTuple,
    RefundProcessedEvent.OutputObject
  >;
  getEvent(
    key: "UserAccepted"
  ): TypedContractEvent<
    UserAcceptedEvent.InputTuple,
    UserAcceptedEvent.OutputTuple,
    UserAcceptedEvent.OutputObject
  >;

  filters: {
    "LinkDecryptedOnChain(address,address)": TypedContractEvent<
      LinkDecryptedOnChainEvent.InputTuple,
      LinkDecryptedOnChainEvent.OutputTuple,
      LinkDecryptedOnChainEvent.OutputObject
    >;
    LinkDecryptedOnChain: TypedContractEvent<
      LinkDecryptedOnChainEvent.InputTuple,
      LinkDecryptedOnChainEvent.OutputTuple,
      LinkDecryptedOnChainEvent.OutputObject
    >;

    "LinkSubmitted(uint256,address)": TypedContractEvent<
      LinkSubmittedEvent.InputTuple,
      LinkSubmittedEvent.OutputTuple,
      LinkSubmittedEvent.OutputObject
    >;
    LinkSubmitted: TypedContractEvent<
      LinkSubmittedEvent.InputTuple,
      LinkSubmittedEvent.OutputTuple,
      LinkSubmittedEvent.OutputObject
    >;

    "MentorWithdraw(address,uint256)": TypedContractEvent<
      MentorWithdrawEvent.InputTuple,
      MentorWithdrawEvent.OutputTuple,
      MentorWithdrawEvent.OutputObject
    >;
    MentorWithdraw: TypedContractEvent<
      MentorWithdrawEvent.InputTuple,
      MentorWithdrawEvent.OutputTuple,
      MentorWithdrawEvent.OutputObject
    >;

    "MentorshipAdded(address,uint256,uint256)": TypedContractEvent<
      MentorshipAddedEvent.InputTuple,
      MentorshipAddedEvent.OutputTuple,
      MentorshipAddedEvent.OutputObject
    >;
    MentorshipAdded: TypedContractEvent<
      MentorshipAddedEvent.InputTuple,
      MentorshipAddedEvent.OutputTuple,
      MentorshipAddedEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "RefundProcessed(address,address,uint256)": TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
    RefundProcessed: TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;

    "UserAccepted(address,address,uint256)": TypedContractEvent<
      UserAcceptedEvent.InputTuple,
      UserAcceptedEvent.OutputTuple,
      UserAcceptedEvent.OutputObject
    >;
    UserAccepted: TypedContractEvent<
      UserAcceptedEvent.InputTuple,
      UserAcceptedEvent.OutputTuple,
      UserAcceptedEvent.OutputObject
    >;
  };
}
